export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

import './globals.css';

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" />
        <link href="https://fonts.googleapis.com/css2?family=Outfit:wght@200&display=swap" rel="stylesheet" />
        <link rel="manifest" href="/manifest.json" />
        <link rel="icon" type="image/png" href="/favicon.png" />
        <script
          dangerouslySetInnerHTML={{
            __html: `
              if ('serviceWorker' in navigator) {
                window.addEventListener('load', function() {
                  navigator.serviceWorker.register('/service-worker.js').then(reg => {
                    // se c'e' un worker in attesa, chiediamo di attivare subito
                    if (reg.waiting) {
                      reg.waiting.postMessage({type: 'SKIP_WAITING'});
                    }

                    reg.addEventListener('updatefound', () => {
                      const newWorker = reg.installing;
                      newWorker.addEventListener('statechange', () => {
                        if (newWorker.state === 'installed' && navigator.serviceWorker.controller) {
                          // nuova versione pronta: ricarica la pagina
                          window.location.reload();
                        }
                      });
                    });
                  });
                });

                // ricarica automatica quando il controller cambia
                navigator.serviceWorker.addEventListener('controllerchange', () => {
                  window.location.reload();
                });
              }
              // Reload for PWA standalone mode
              if (window.matchMedia('(display-mode: standalone)').matches) {
                window.addEventListener('visibilitychange', function() {
                  if (document.visibilityState === 'visible') {
                    window.location.reload();
                  }
                });
              }
            `
          }}
        />
      </head>
      <body>{children}</body>
    </html>
  );
}
